# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: create kube folder
      run: mkdir ${HOME}/.kube
    - uses: akiojin/decode-base64-github-action@v0.1.0
      id: decode-base64
      with:
        base64: ${{ secrets.KUBE_CONFIG }}
        output-path: ${HOME}/.kube/config
    - run: |
        echo ${{ steps.decode-base64.outputs.decoded }}
    # - name: kubeconfig setup
    #   run: |
    #     env:
    #       KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #     mkdir ${HOME}/.kube
    #     echo ${HOME}
    #     echo $KUBE_CONFIG | base64 --decode > ${HOME}/.kube/config
    #     cat ${HOME}/.kube/config
    - name: switch to dev context
      run: kubectl get po

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
